project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - posts/*.qmd
    - life/*.qmd
    - resume.qmd

website:
  title: "Crrow Blog"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: posts/index.qmd
        text: Posts
      - href: life/index.qmd
        text: Life
      - href: resume.qmd
        text: Resume
  page-footer:
    left: "Copyright 2025"

format:
  html:
    theme:
      light:
        - cosmo
        - styles-light.scss
      dark:
        - darkly
        - styles-dark.scss
    toc: true
