project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - posts/*.qmd

website:
  title: "Crrow Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts/index.qmd
        text: Posts
  page-footer:
    left: "Copyright 2025"

format:
  html:
    theme: cosmo
    toc: true
